default_language_version:
  python: python

repos:
  - repo: local
    hooks:
      - id: yapf
        name: yapf
        entry: poetry run yapf
        language: system
        types_or: [python]
        args: ["-i"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.389  # o la última versión estable
    hooks:
      - id: pyright
        additional_dependencies: []

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run pytest
        language: system
        pass_filenames: false