DROP TABLE "TDB"."TDB_CONF";
--------------------------------------------------------
--  DDL for Sequence TDB_CNF_ID
--------------------------------------------------------

drop sequence "TDB"."TDB_CNF_ID";
CREATE SEQUENCE "TDB"."TDB_CNF_ID";
--------------------------------------------------------
--  DDL for Table TDB_CONF
--------------------------------------------------------

CREATE TABLE "TDB"."TDB_CONF" 
(
    "CNF_ID" NUMBER, 
    "CNF_PROD_OWNER" VARCHAR2(50 BYTE), 
    "CNF_HIST_OWNER" VARCHAR2(50 BYTE), 
    "CNF_TABLE" VARCHAR2(50 BYTE), 
    "CNF_MONTHS_KEEP_PROD" NUMBER, 
    "CNF_MONTHS_KEEP_HIST" NUMBER, 
    "CNF_EXEC_DAY" VARCHAR2(10 BYTE), 
    "CNF_FRECUENCY" VARCHAR2(10 BYTE), 
    "CNF_IS_ACTIVE" CHAR(1 BYTE), 
    "CNF_PURGE_LIMIT_DATE_EXPR" VARCHAR2(100 BYTE), 
    "CNF_ADDITIONAL_EXPR" VARCHAR2(4000 BYTE), 
    "CNF_PROD_ORPHAN_PURGE" CHAR(1 BYTE), 
    "CNF_ORPHAN_CHK_COLUMN" VARCHAR2(4000 BYTE), 
    "CNF_HAS_LOB" CHAR(1 BYTE), 
    "CNF_REF_TABLES" VARCHAR2(100 BYTE), 
    "CNF_JOIN_EXPR" VARCHAR2(4000 BYTE), 
    "CNF_HINT_EXPR" VARCHAR2(4000 BYTE), 
    "CNF_LONG_COLS" VARCHAR2(4000 BYTE)
);

--------------------------------------------------------
--  DDL for Index CNF_CONF_PK
--------------------------------------------------------

CREATE UNIQUE INDEX "TDB"."CNF_CONF_PK" ON "TDB"."TDB_CONF" ("CNF_ID");

--------------------------------------------------------
--  DDL for Index CNF_CONF_I1
--------------------------------------------------------

CREATE INDEX "TDB"."CNF_CONF_I1" ON "TDB"."TDB_CONF" ("CNF_PROD_OWNER", "CNF_TABLE");

--------------------------------------------------------
--  Constraints for Table TDB_CONF
--------------------------------------------------------

ALTER TABLE "TDB"."TDB_CONF" ADD CONSTRAINT "CNF_CONF_PK" PRIMARY KEY ("CNF_ID") USING INDEX;

--------------------------------------------------------
--  DDL for Trigger TDB_CNF_ID_CR
--------------------------------------------------------

CREATE OR REPLACE EDITIONABLE TRIGGER "TDB"."TDB_CNF_CR" 
    before insert on "TDB_CONF" 
    for each row 
begin  
    if inserting then 
        if :NEW."CNF_ID" is null then 
            select TDB_CNF_ID.nextval into :NEW."CNF_ID" from dual; 
        end if; 
    end if; 
end;
/
ALTER TRIGGER "TDB"."TDB_CNF_CR" ENABLE;

REM INSERTING into TDB.TDB_CONF
SET DEFINE OFF;
Insert into TDB.TDB_CONF (CNF_PROD_OWNER,CNF_HIST_OWNER,CNF_TABLE,CNF_MONTHS_KEEP_PROD,CNF_MONTHS_KEEP_HIST,CNF_EXEC_DAY,CNF_FRECUENCY,CNF_IS_ACTIVE,CNF_PURGE_LIMIT_DATE_EXPR,CNF_ADDITIONAL_EXPR,CNF_PROD_ORPHAN_PURGE,CNF_ORPHAN_CHK_COLUMN,CNF_HAS_LOB,CNF_REF_TABLES,CNF_JOIN_EXPR,CNF_HINT_EXPR,CNF_LONG_COLS) values ('GL','GLHST','INV_HEAD','3','11',null,'D','Y','INV_DSP_DATE','A.INV_STATUS=''D''',null,null,'N',null,null,'full(A)',null);
Insert into TDB.TDB_CONF (CNF_PROD_OWNER,CNF_HIST_OWNER,CNF_TABLE,CNF_MONTHS_KEEP_PROD,CNF_MONTHS_KEEP_HIST,CNF_EXEC_DAY,CNF_FRECUENCY,CNF_IS_ACTIVE,CNF_PURGE_LIMIT_DATE_EXPR,CNF_ADDITIONAL_EXPR,CNF_PROD_ORPHAN_PURGE,CNF_ORPHAN_CHK_COLUMN,CNF_HAS_LOB,CNF_REF_TABLES,CNF_JOIN_EXPR,CNF_HINT_EXPR,CNF_LONG_COLS) values ('GL','GLHST','INV_HEAD','1','5',null,'D','Y','INV_DATE','A.INV_STATUS=''A''',null,null,'N',null,null,'full(A)',null);
Insert into TDB.TDB_CONF (CNF_PROD_OWNER,CNF_HIST_OWNER,CNF_TABLE,CNF_MONTHS_KEEP_PROD,CNF_MONTHS_KEEP_HIST,CNF_EXEC_DAY,CNF_FRECUENCY,CNF_IS_ACTIVE,CNF_PURGE_LIMIT_DATE_EXPR,CNF_ADDITIONAL_EXPR,CNF_PROD_ORPHAN_PURGE,CNF_ORPHAN_CHK_COLUMN,CNF_HAS_LOB,CNF_REF_TABLES,CNF_JOIN_EXPR,CNF_HINT_EXPR,CNF_LONG_COLS) values ('GL','GLHST','INV_DET',null,null,null,null,null,null,null,'Y','INV_ID B','N','INV_HEAD','JOIN INV_HEAD ON B.INV_ID=A.INV_ID','full(A) full(B) use_hash(A, B)',null);
Insert into TDB.TDB_CONF (CNF_PROD_OWNER,CNF_HIST_OWNER,CNF_TABLE,CNF_MONTHS_KEEP_PROD,CNF_MONTHS_KEEP_HIST,CNF_EXEC_DAY,CNF_FRECUENCY,CNF_IS_ACTIVE,CNF_PURGE_LIMIT_DATE_EXPR,CNF_ADDITIONAL_EXPR,CNF_PROD_ORPHAN_PURGE,CNF_ORPHAN_CHK_COLUMN,CNF_HAS_LOB,CNF_REF_TABLES,CNF_JOIN_EXPR,CNF_HINT_EXPR,CNF_LONG_COLS) values ('GL','GLHST','DSP_HEAD','3','11',null,'D','Y','DSP_DATE','A.DSP_STATUS=''D''',null,null,'N',null,null,'full(A)',null);
Insert into TDB.TDB_CONF (CNF_PROD_OWNER,CNF_HIST_OWNER,CNF_TABLE,CNF_MONTHS_KEEP_PROD,CNF_MONTHS_KEEP_HIST,CNF_EXEC_DAY,CNF_FRECUENCY,CNF_IS_ACTIVE,CNF_PURGE_LIMIT_DATE_EXPR,CNF_ADDITIONAL_EXPR,CNF_PROD_ORPHAN_PURGE,CNF_ORPHAN_CHK_COLUMN,CNF_HAS_LOB,CNF_REF_TABLES,CNF_JOIN_EXPR,CNF_HINT_EXPR,CNF_LONG_COLS) values ('GL','GLHST','DSP_HEAD','1','5',null,'D','Y','DSP_DATE','A.DSP_STATUS=''A''',null,null,'N',null,null,'full(A)',null);
Insert into TDB.TDB_CONF (CNF_PROD_OWNER,CNF_HIST_OWNER,CNF_TABLE,CNF_MONTHS_KEEP_PROD,CNF_MONTHS_KEEP_HIST,CNF_EXEC_DAY,CNF_FRECUENCY,CNF_IS_ACTIVE,CNF_PURGE_LIMIT_DATE_EXPR,CNF_ADDITIONAL_EXPR,CNF_PROD_ORPHAN_PURGE,CNF_ORPHAN_CHK_COLUMN,CNF_HAS_LOB,CNF_REF_TABLES,CNF_JOIN_EXPR,CNF_HINT_EXPR,CNF_LONG_COLS) values ('GL','GLHST','DSP_DET',null,null,null,null,null,null,null,'Y','B.DSP_ID, C.IND_ID','N','DSP_HEAD, INV_DET','JOIN DSP_HEAD B ON B.DSP_ID=A.DSP_ID JOIN INV_DET C ON C.IND_ID = A.IND_ID','full(A) full(B) full(C) use_hash(A, B, C)',null);

commit;